a = input("Enter your name: ")
grade = input("Enter your grade: ")
print("Hello, " + a + "! You are in grade " + grade + ". Welcome to vscode!")
print("Welcome to the world of programming!")
print(4)
print("Hello, \nWorld!")
print("All keywords of python are below:")
help("keywords")
help("modules")