classmates=["Alex","Jordan","Taylor","Morgan","Casey"]
print("Classmates List:", classmates)
print("Total students in the class:", len(classmates))
print("First student in the list:", classmates[0])
print("Last student in the list:", classmates[-1])
print("Students from index 1 to 3:", classmates[1:4])
print("Students in reverse order:", classmates[::-1])
print("Second student in the list:", classmates[1])
print("Third student in the list:", classmates[2])
print("Fourth student in the list:", classmates[3])
print("Fifth student in the list:", classmates[4])
classmates.append("Riley")
print("\nAfter adding Riley:", classmates)
classmates.remove("Taylor")
print("After removing Taylor:", classmates)
classmates.sort()
print("Sorted classmates list:", classmates)
classmates.reverse()
print("Reversed classmates list:", classmates)
